#pragma once
#include <unordered_map>

namespace HaloScriptCommon
{
	static const std::unordered_map <int, std::string> tag_group_names
	{
		{ '$#!+', "cache_file_sound" },
		{ '*cen', "scenario_scenery_resource" },
		{ '*eap', "scenario_weapons_resource" },
		{ '*ehi', "scenario_vehicles_resource" },
		{ '*igh', "scenario_lights_resource" },
		{ '*ipd', "scenario_bipeds_resource" },
		{ '*qip', "scenario_equipment_resource" },
		{ '*rea', "scenario_creature_resource" },
		{ '*sce', "scenario_sound_scenery_resource" },
		{ '/**/', "scenario_comments_resource" },
		{ '<fx>', "sound_effect_template" },
		{ 'BooM', "stereo_system" },
		{ 'DECP', "decorators" },
		{ 'DECR', "decorator_set" },
		{ 'MGS2', "light_volume" },
		{ 'PRTM', "particle_model" },
		{ 'adlg', "ai_dialogue_globals" },
		{ 'ai**', "scenario_ai_resource" },
		{ 'ant!', "antenna" },
		{ 'bipd', "biped" },
		{ 'bitm', "bitmap" },
		{ 'bloc', "crate" },
		{ 'bsdt', "breakable_surface" },
		{ 'char', "character" },
		{ 'cin*', "scenario_cinematics_resource" },
		{ 'clu*', "scenario_cluster_data_resource" },
		{ 'clwd', "cloth" },
		{ 'coll', "collision_model" },
		{ 'coln', "colony" },
		{ 'colo', "color_table" },
		{ 'cont', "contrail" },
		{ 'crea', "creature" },
		{ 'ctrl', "device_control" },
		{ 'dc*s', "scenario_decorators_resource" },
		{ 'dec*', "scenario_decals_resource" },
		{ 'deca', "decal" },
		{ 'devi', "device" },
		{ 'devo', "cellular_automata" },
		{ 'dgr*', "scenario_devices_resource" },
		{ 'dobc', "detail_object_collection" },
		{ 'effe', "effect" },
		{ 'egor', "screen_effect" },
		{ 'eqip', "equipment" },
		{ 'fog ', "planar_fog" },
		{ 'foot', "material_effects" },
		{ 'fpch', "patchy_fog" },
		{ 'garb', "garbage" },
		{ 'gldf', "chocolate_mountain" },
		{ 'goof', "multiplayer_variant_settings_interface_definition" },
		{ 'grhi', "grenade_hud_interface" },
		{ 'hlmt', "model" },
		{ 'hmt ', "hud_message_text" },
		{ 'hsc*', "scenario_hs_source_file" },
		{ 'hud#', "hud_number" },
		{ 'hudg', "hud_globals" },
		{ 'item', "item" },
		{ 'itmc', "item_collection" },
		{ 'jmad', "model_animation_graph" },
		{ 'jpt!', "damage_effect" },
		{ 'lens', "lens_flare" },
		{ 'lifi', "device_light_fixture" },
		{ 'ligh', "light" },
		{ 'lsnd', "sound_looping" },
		{ 'ltmp', "scenario_structure_lightmap" },
		{ 'mach', "device_machine" },
		{ 'matg', "globals" },
		{ 'mcsr', "mouse_cursor_definition" },
		{ 'mdlg', "ai_mission_dialogue" },
		{ 'metr', "meter" },
		{ 'mode', "render_model" },
		{ 'mpdt', "material_physics" },
		{ 'mply', "multiplayer_scenario_description" },
		{ 'mulg', "multiplayer_globals" },
		{ 'nhdt', "new_hud_definition" },
		{ 'obje', "object" },
		{ 'phmo', "physics_model" },
		{ 'phys', "physics" },
		{ 'pixl', "pixel_shader" },
		{ 'pmov', "particle_physics" },
		{ 'pphy', "point_physics" },
		{ 'proj', "projectile" },
		{ 'prt3', "particle" },
		{ 'sbsp', "scenario_structure_bsp" },
		{ 'scen', "scenery" },
		{ 'scnr', "scenario" },
		{ 'sfx+', "sound_effect_collection" },
		{ 'shad', "shader" },
		{ 'sily', "text_value_pair_definition" },
		{ 'skin', "user_interface_list_skin_definition" },
		{ 'sky ', "sky" },
		{ 'slit', "shader_light_response" },
		{ 'sncl', "sound_classes" },
		{ 'snd!', "sound" },
		{ 'snde', "sound_environment" },
		{ 'snmx', "sound_mix" },
		{ 'spas', "shader_pass" },
		{ 'spk!', "sound_dialogue_constants" },
		{ 'ssce', "sound_scenery" },
		{ 'sslt', "scenario_structure_lighting_resource" },
		{ 'stem', "shader_template" },
		{ 'styl', "style" },
		{ 'tdtl', "liquid" },
		{ 'trak', "camera_track" },
		{ 'trg*', "scenario_trigger_volumes_resource" },
		{ 'udlg', "dialogue" },
		{ 'ugh!', "sound_cache_file_gestalt" },
		{ 'unhi', "unit_hud_interface" },
		{ 'unic', "multilingual_unicode_string_list" },
		{ 'unit', "unit" },
		{ 'vehc', "vehicle_collection" },
		{ 'vehi', "vehicle" },
		{ 'vrtx', "vertex_shader" },
		{ 'weap', "weapon" },
		{ 'weat', "weather_system" },
		{ 'wgit', "user_interface_screen_widget_definition" },
		{ 'wgtz', "user_interface_globals_definition" },
		{ 'whip', "cellular_automata2d" },
		{ 'wigl', "user_interface_shared_globals_definition" },
		{ 'wind', "wind" },
		{ 'wphi', "weapon_hud_interface" },
	};

	const int string_to_tag_group(const std::string &contents)
	{
		auto i = std::find_if(tag_group_names.begin(), tag_group_names.end(),
			[contents](std::pair<const int, const std::string> i) -> bool
			{
				return i.second == contents;
			}
		);
		if (i == tag_group_names.end()) {
			return NONE;
		}
		else {
			return i->first;
		}
	}
}
